<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/favicon.ico">

    <title>Have a try</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/cover.css" rel="stylesheet">
</head>

<body class="text-center">

<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto"></header>
    <main role="main" class="inner cover">
        <h1 class="cover-heading">Have a try</h1>
        <p class="lead">Whatever you should be doing right now , go fucking do it.</p>
        <input type="text" name="tmall_name" class="form-control" placeholder="Store Name" required autofocus>
        <p class="lead mt-2">
            <a href="javascript:;" id="check" class="btn btn-secondary">Learn more</a>
        </p>
    </main>
    <footer class="mastfoot mt-auto">
        <div class="inner">
            <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
        </div>
    </footer>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/js/jquery-1.9.1.min.js"></script>
<!--<script src="/js/jquery-slim.min.js"></script>-->
<script src="/js/popper.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script>
    $('#check').click(function () {
        var name = $('input[name="tmall_name"]').val();
        get_info(name)
    })

    var get_info = function (name) {
        var data = {name: name,<?php echo $this->security->getTokenKey() ?>:'<?php echo $this->security->getToken() ?>'};
        $.ajax({
            url: '/tmall',
            data: data,
            type: 'POST',
            dataType: 'JSON',
            success: function (json) {
            }
        })
    }
</script>
</body>
</html>
